### ISSUE TITLE
Is pdf_to_csv.py not Python3 ready ?

### ISSUE THREAD

**Issue by fx86** [cbgaindia/parsers#41]
Cloned the repo and executed `python pdf_to_csv.py`. 

Got this error : 
```
Traceback (most recent call last):
  File "pdf_to_csv.py", line 9, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

Replaced this with configparser (as it is named in Python3) and got the following error :
```
Traceback (most recent call last):
  File "pdf_to_csv.py", line 16, in <module>
    fileConfig('parsers/logging_config.ini')
  File "/Users/fibinse/anaconda3/lib/python3.6/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/Users/fibinse/anaconda3/lib/python3.6/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/Users/fibinse/anaconda3/lib/python3.6/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```
Is this script only-Python2 compliant ?

**Comment by gggodhwani** [comment]
At this moment yes, its not Python 3 ready. Though we welcome pull requests from the community to help us migrate towards Python 2 & Python 3 compatible code.
